name: CI

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 20.0.2
      uses: actions/setup-java@v2
      with:
        java-version: 20.0.2
        distribution: 'adopt'
    - name: clean and build
      run: chmod +x ./gradlew && ./gradlew clean test --info --stacktrace

